version: '3'
services:
  api:
    build: ./api
    command: gunicorn -w 1 --bind 0.0.0.0:8000 api.wsgi
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"